### ISSUE TITLE
Authcode not correct for my second steam account.

### ISSUE THREAD

**Issue by Govind13100** [DoctorMcKay/php-steam-totp#2]
Authcode for my first steam account worked correctly and I got the cookies and session id. But for second steam account the authcode is incorrect. I can't get the cookies and session id using authcode generated by this script. 

I don't know why this happening. Do you have any idea about it ??? 

Does shared_secret always have a fixed syntax ??

**Comment by DoctorMcKay** [comment]
If the code is wrong, either your secret is wrong or your time is wrong.

**Comment by Govind13100** [comment]
I got the solution, My localhost was wrong, on live server running awesome. 

By the way thank you for the script :-)
